spring:
  redis:
    password: aexMNwQNmxgu9Bvv
    sentinel:
      nodes: redis-sentinel01.test.geely.com:6391
      master: sentinel-10.190.64.90-6390
    lettuce:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）